version: "1.7"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      DATABASE_URL: $DATABASE_URL
      MUST_JOIN: $MUST_JOIN
      ENVIRONMENT: $ENVIRONMENT